on:  
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build
      - run: sam build --use-container
# Run Unit tests-Specify unit tests here
# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-front-end --s3-bucket gnguyendo-cloud-resume-front-end-template --capabilities CAPABILITY_NAMED_IAM --region us-east-1

  sync-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
        uses: actions/checkout@v3
      - run: aws s3 sync ./public s3://gnguyendo-cloud-resume-website
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'us-east-1'

  upload_lambda_function:
    runs-on: ubuntu-latest
    steps:
      - name: Upload to S3
        uses: actions/checkout@v3
      - run: zip -r lambdadeploymentpackage.zip main
      - run: aws s3 cp lambdadeploymentpackage.zip s3://gnguyendo-cloud-resume-front-end-template
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: 'us-east-1'